name: Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: robticorg/robtic-actions/.github/workflows/deploy.yml@main
    with:
      deploy-type: docker
      runner-labels: '["self-hosted", "robtic-deploy"]'
      environment-name: 'Robtic Server'
      environment-url: 'https://robtic.org'
      server-label: 'core.robtic.org'
      compose-project-name: 'robtic-system'
      compose-env-file: '/home/robtic/robtic-system/.env'
    secrets:
      DISCORD_WEBHOOK_DEPLOY: ${{ secrets.DISCORD_WEBHOOK_DEPLOY }}
